export const actions = {
	blog: {
		DATA_FETCHING: "BLOG_DATA_FETCHING",
		DATA_FETCHED: "BLOG_DATA_FETCHED",
		DATA_ERROR: "BLOG_FETCHED_ERROR",
		DATA_CLEAN: "BLOG_FETCHED_CLEAN",
		BLOG_CREATED: "BLOG_CREATED",
		BLOG_DELETED: "BLOG_DELETED",
	},
	post: {
		DATA_FETCHING: "POST_DATA_FETCHING",
		DATA_FETCHED: "POST_DATA_FETCHED",
		DATA_ERROR: "POST_FETCHED_ERROR",
	},
	singleBlog: {
		DATA_FETCHING: "SINGLE_DATA_FETCHING",
		DATA_FETCHED: "SINGLE_DATA_FETCHED",
		DATA_ERROR: "SINGLE_FETCHED_ERROR",
		DATA_CLEAN: "SINGLE_FETCHED_CLEAN",
		BLOG_FAVOURITED: "BLOG_FAVOURITED",
		BLOG_LIKED: "BLOG_LIKED",
		BLOG_COMMENTS: "SINGLE_COMMENTS",
		COMMENT_POST: "COMMENT_POST",
		COMMENT_DELETE: "COMMENT_DELETE",
	},
	userAuth: {
		DATA_AUTh: "USER_DATA_AUTH",
		LOGGED_OUT: "LOGGED_OUT",
	},
	authorBlog: {
		AUTHOR_BLOG: "AUTHOR_BLOG",
		AUTHOR_BLOG_DELETE: "AUTHOR_BLOG_DELETE",
	},
};
